const adverbsData = [
  {
		sentence1: "Jean joue",
		adverb: "sagement",
		sentence2:"",
		itemType: "adverb",
		id: 1,
		valid: true,
		shapeFeatures: {
			canBeAResponseToHowQuestion: true,
			canBeAResponseToWhereQuestion: false,
			canBeAResponseToWhenQuestion: false,
			showingIntensity: false,
			showingManner: true,
			isANegation: false,
			isAnAffirmation: false,
			isAGroupOfWords: false,
			isASimpleWord: true,
			endingWithAmment: false,
			endingWithEmment: false,
			endingWithEment: true,
			endingWithMent: true,
			AffectingTheVerb: true,
			AffectingAllTheProposition: false,
			AffectingTheAdjective: false,
		}
	},
	{
		sentence1:"Jeanne est",
		adverb: "très",
		sentence2:"mignonne",
		itemType: "adverb",
		id: 2,
		valid: true,
		shapeFeatures: {
			canBeAResponseToHowQuestion: false,
			canBeAResponseToWhereQuestion: false,
			canBeAResponseToWhenQuestion: false,
			showingIntensity: true,
			showingManner: false,
			isANegation: false,
			isAnAffirmation: false,
			isAGroupOfWords: false,
			isASimpleWord: true,
			endingWithAmment: false,
			endingWithEmment: false,
			endingWithEment: false,
			endingWithMent: false,
			AffectingTheVerb: false,
			AffectingAllTheProposition: false,
			AffectingTheAdjective: true,
		}
	},
	{
		sentence1:"Il parle",
		adverb: "doucement",
		sentence2:"",
		itemType: "adverb",
		id: 3,
		valid: true,
		shapeFeatures: {
			canBeAResponseToHowQuestion: true,
			canBeAResponseToWhereQuestion: false,
			canBeAResponseToWhenQuestion: false,
			showingIntensity: false,
			showingManner: true,
			isANegation: false,
			isAnAffirmation: false,
			isAGroupOfWords: false,
			isASimpleWord: true,
			endingWithAmment: false,
			endingWithEmment: false,
			endingWithEment: true,
			endingWithMent: true,
			AffectingTheVerb: true,
			AffectingAllTheProposition: false,
			AffectingTheAdjective: false,
		}
	},
	{
		sentence1:"Nous sommes rentrés",
		adverb: "tard",
		sentence2:"",
		itemType: "adverb",
		id: 4,
		valid: true,
		shapeFeatures: {
			canBeAResponseToHowQuestion: false,
			canBeAResponseToWhereQuestion: false,
			canBeAResponseToWhenQuestion: true,
			showingIntensity: false,
			showingManner: false,
			isANegation: false,
			isAnAffirmation: false,
			isAGroupOfWords: false,
			isASimpleWord: true,
			endingWithAmment: false,
			endingWithEmment: false,
			endingWithEment: false,
			endingWithMent: false,
			AffectingTheVerb: false,
			AffectingAllTheProposition: false,
			AffectingTheAdjective: false,
		}
	},
	{
		sentence1:"Ils habitent",
		adverb: "loin",
		sentence2:"",
		itemType: "adverb",
		id: 5,
		valid: true,
		shapeFeatures: {
			canBeAResponseToHowQuestion: false,
			canBeAResponseToWhereQuestion: true,
			canBeAResponseToWhenQuestion: false,
			showingIntensity: false,
			showingManner: false,
			isANegation: false,
			isAnAffirmation: false,
			isAGroupOfWords: false,
			isASimpleWord: true,
			endingWithAmment: false,
			endingWithEmment: false,
			endingWithEment: false,
			endingWithMent: false,
			AffectingTheVerb: false,
			AffectingAllTheProposition: false,
			AffectingTheAdjective: false,
		}
	},
	{
		sentence1:"Ils ont",
		adverb: "beacoup",
		sentence2:"d'examens la semaine prochaine",
		itemType: "adverb",
		id: 6,
		valid: true,
		shapeFeatures: {
			canBeAResponseToHowQuestion: false,
			canBeAResponseToWhereQuestion: false,
			canBeAResponseToWhenQuestion: false,
			showingIntensity: true,
			showingManner: false,
			isANegation: false,
			isAnAffirmation: false,
			isAGroupOfWords: false,
			isASimpleWord: true,
			endingWithAmment: false,
			endingWithEmment: false,
			endingWithEment: false,
			endingWithMent: false,
			AffectingTheVerb: false,
			AffectingAllTheProposition: false,
			AffectingTheAdjective: false,
		}
	},
	{
		sentence1:"Il eu",
		adverb: "assez",
		sentence2:"de problèmes aujourd'hui",
		itemType: "adverb",
		id: 7,
		valid: true,
		shapeFeatures: {
			canBeAResponseToHowQuestion: false,
			canBeAResponseToWhereQuestion: false,
			canBeAResponseToWhenQuestion: false,
			showingIntensity: true,
			showingManner: false,
			isANegation: false,
			isAnAffirmation: false,
			isAGroupOfWords: false,
			isASimpleWord: true,
			endingWithAmment: false,
			endingWithEmment: false,
			endingWithEment: false,
			endingWithMent: false,
			AffectingTheVerb: false,
			AffectingAllTheProposition: false,
			AffectingTheAdjective: false,
		}
	},
	{
		sentence1:"Il habite",
		adverb: "près",
		sentence2:"de l'école",
		itemType: "adverb",
		id: 8,
		valid: true,
		shapeFeatures: {
			canBeAResponseToHowQuestion: false,
			canBeAResponseToWhereQuestion: true,
			canBeAResponseToWhenQuestion: false,
			showingIntensity: false,
			showingManner: false,
			isANegation: false,
			isAnAffirmation: false,
			isAGroupOfWords: false,
			isASimpleWord: true,
			endingWithAmment: false,
			endingWithEmment: false,
			endingWithEment: false,
			endingWithMent: false,
			AffectingTheVerb: false,
			AffectingAllTheProposition: false,
			AffectingTheAdjective: false,
		}
	},
	{
		sentence1:"",
		adverb: "parfois",
		sentence2:",il fait beau à Londres",
		itemType: "adverb",
		id: 9,
		valid: true,
		shapeFeatures: {
			canBeAResponseToHowQuestion: false,
			canBeAResponseToWhereQuestion: false,
			canBeAResponseToWhenQuestion: true,
			showingIntensity: false,
			showingManner: false,
			isANegation: false,
			isAnAffirmation: false,
			isAGroupOfWords: false,
			isASimpleWord: true,
			endingWithAmment: false,
			endingWithEmment: false,
			endingWithEment: false,
			endingWithMent: false,
			AffectingTheVerb: false,
			AffectingAllTheProposition: false,
			AffectingTheAdjective: false,
		}
	},
	{
		sentence1:"il n'a",
		adverb: "jamais",
		sentence2:"eu l'occasion de faire de la pêche",
		itemType: "adverb",
		id: 10,
		valid: true,
		shapeFeatures: {
			canBeAResponseToHowQuestion: false,
			canBeAResponseToWhereQuestion: false,
			canBeAResponseToWhenQuestion: false,
			showingIntensity: false,
			showingManner: false,
			isANegation: true,
			isAnAffirmation: false,
			isAGroupOfWords: false,
			isASimpleWord: true,
			endingWithAmment: false,
			endingWithEmment: false,
			endingWithEment: false,
			endingWithMent: false,
			AffectingTheVerb: false,
			AffectingAllTheProposition: false,
			AffectingTheAdjective: false,
		}
	},
	{
		sentence1:"",
		adverb: "peut-être",
		sentence2:"qu'il fera son master à l'EPFZ",
		itemType: "adverb",
		id: 11,
		valid: true,
		shapeFeatures: {
			canBeAResponseToHowQuestion: false,
			canBeAResponseToWhereQuestion: false,
			canBeAResponseToWhenQuestion: false,
			showingIntensity: false,
			showingManner: false,
			isANegation: false,
			isAnAffirmation: true,
			isAGroupOfWords: false,
			isASimpleWord: true,
			endingWithAmment: false,
			endingWithEmment: false,
			endingWithEment: false,
			endingWithMent: false,
			AffectingTheVerb: false,
			AffectingAllTheProposition: false,
			AffectingTheAdjective: false,
		}
	},
	{
		sentence1:"Le rapport a été publié",
		adverb: "récemment",
		sentence2:"sur notre site",
		itemType: "adverb",
		id: 12,
		valid: true,
		shapeFeatures: {
			canBeAResponseToHowQuestion: false,
			canBeAResponseToWhereQuestion: false,
			canBeAResponseToWhenQuestion: true,
			showingIntensity: false,
			showingManner: false,
			isANegation: false,
			isAnAffirmation: false,
			isAGroupOfWords: false,
			isASimpleWord: true,
			endingWithAmment: false,
			endingWithEmment: true,
			endingWithEment: false,
			endingWithMent: true,
			AffectingTheVerb: false,
			AffectingAllTheProposition: false,
			AffectingTheAdjective: false,
		}
	},
	{
		sentence1:"Ils m'ont",
		adverb: "gentiment",
		sentence2:"fait comprendre que je devais quitter la salle",
		itemType: "adverb",
		id: 13,
		valid: true,
		shapeFeatures: {
			canBeAResponseToHowQuestion: true,
			canBeAResponseToWhereQuestion: false,
			canBeAResponseToWhenQuestion: false,
			showingIntensity: false,
			showingManner: false,
			isANegation: false,
			isAnAffirmation: false,
			isAGroupOfWords: false,
			isASimpleWord: true,
			endingWithAmment: false,
			endingWithEmment: false,
			endingWithEment: false,
			endingWithMent: true,
			AffectingTheVerb: false,
			AffectingAllTheProposition: false,
			AffectingTheAdjective: false,
		}
	},
	{
		sentence1:"Le professeur a",
		adverb: "brièvement",
		sentence2:"rappelé le cours",
		itemType: "adverb",
		id: 14,
		valid: true,
		shapeFeatures: {
			canBeAResponseToHowQuestion: true,
			canBeAResponseToWhereQuestion: false,
			canBeAResponseToWhenQuestion: false,
			showingIntensity: false,
			showingManner: false,
			isANegation: false,
			isAnAffirmation: false,
			isAGroupOfWords: false,
			isASimpleWord: true,
			endingWithAmment: false,
			endingWithEmment: false,
			endingWithEment: true,
			endingWithMent: true,
			AffectingTheVerb: true,
			AffectingAllTheProposition: false,
			AffectingTheAdjective: false,
		}
	},
	{
		sentence1:"Il avance",
		adverb: "lentement",
		sentence2:"",
		itemType: "adverb",
		id: 15,
		valid: true,
		shapeFeatures: {
			canBeAResponseToHowQuestion: true,
			canBeAResponseToWhereQuestion: false,
			canBeAResponseToWhenQuestion: false,
			showingIntensity: false,
			showingManner: true,
			isANegation: false,
			isAnAffirmation: false,
			isAGroupOfWords: false,
			isASimpleWord: true,
			endingWithAmment: false,
			endingWithEmment: false,
			endingWithEment: true,
			endingWithMent: true,
			AffectingTheVerb: true,
			AffectingAllTheProposition: false,
			AffectingTheAdjective: false,
		}
	},
	{
		sentence1:"Il est revenu nous voir",
		adverb: "avant-hier",
		sentence2:"",
		itemType: "adverb",
		id: 16,
		valid: true,
		shapeFeatures: {
			canBeAResponseToHowQuestion: false,
			canBeAResponseToWhereQuestion: false,
			canBeAResponseToWhenQuestion: true,
			showingIntensity: false,
			showingManner: false,
			isANegation: false,
			isAnAffirmation: false,
			isAGroupOfWords: true,
			isASimpleWord: false,
			endingWithAmment: false,
			endingWithEmment: false,
			endingWithEment: false,
			endingWithMent: false,
			AffectingTheVerb: false,
			AffectingAllTheProposition: false,
			AffectingTheAdjective: false,
		}
	}
    
].sort(() => 0.5 - Math.random());


export default adverbsData;